config/routes.rb
Gmaps::Application.routes.draw do
  resources :characters
  root :to => 'characters#index'

end

app/models/character.rb
class Character < ActiveRecord::Base
  acts_as_gmappable
  attr_accessible :address, :gmaps, :latitude, :longitude, :name

  def gmaps4rails_address
    address
  end

  def gmaps4rails_infowindow 
    "<h1>#{name} #{address}</h1>"
  end

  def gmaps4rails_marker_picture
	{
		"picture" => "/assets/placemarker.png",
		"width" => 60,
		"height" => 60 
	}
	end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all
    @json       = Character.all.to_gmaps4rails
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @characters }
    end
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
    @character = Character.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @character }
    end
  end

  # GET /characters/new
  # GET /characters/new.json
  def new
    @character = Character.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @character }
    end
  end

  # GET /characters/1/edit
  def edit
    @character = Character.find(params[:id])
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(params[:character])

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'New place created!' }
        format.json { render json: @character, status: :created, location: @character }
      else
        format.html { render action: "index" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /characters/1
  # PUT /characters/1.json
  def update
    @character = Character.find(params[:id])

    respond_to do |format|
      if @character.update_attributes(params[:character])
        format.html { redirect_to @character, notice: 'Place successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "index" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character = Character.find(params[:id])
    @character.destroy

    respond_to do |format|
      format.html { redirect_to characters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_for(@character) do |f| %>

<div class="places-container">

              <h3>Place Name</h3>
              <%= f.text_field :name, :class =>"places-formbox-wrapper", :placeholder => " ex. 'Dentist', 'Work', 'Grandma's House'" %>
  
              <h3>Place Address</h3>
               <%= f.text_field :address, :class =>"places-formbox-wrapper", :placeholder => " 34 Valley Road Walla Walla, WA 99362" %>

          <div class="places_buttonbox">

              <%= f.submit "Save place", :class => "places_button" %>

              <%= link_to 'Back to Places', characters_path, :class => "places_button2" %>

          </div> <!-- end places-buttonbox -->
   
</div> <!-- end places container -->

<% end %>

app/views/characters/_places-footer.html.erb
<div class="master-footer places-footer">
	<ul>
            <li><h5>©2013<a href="http://www.about.me/dantashman" target="_blank"> Dan Tashman</a></h5></li>
            <li><a href="index.html"><img src="images/house.png" width="32" height="32" alt="home-icon" /></a></li>
           <li><h6><a href="FAQ.html">FAQ's</a></h6></li>
           <li><h6><a href="about.html">About/Contact</h6></a></li>
           <li><h6><a href="espanol.html">Virgil en Espanol</h6></a></li>
         
     </ul>
</div> 

app/views/characters/_places-header.html.erb
<div class="master-header places-header">
         <%= link_to image_tag ('Virgil-Logo.png') %>
         <h2>Virgil: Places</h2>
        <h3>Welcome, <%= @first_name %></h3>
        <div class="bumper places-bumper"></div>
</div> <!--end master header-->

app/views/characters/edit.html.erb
<%= render 'places-header' %>

<div class="white">
	<%= render 'form' %>
</end>

<%= render 'places-footer' %>

app/views/characters/index.html.erb
<%= render 'places-header' %>

<div class="places-headroom"></div>

<div class="plces-container">

  <%= link_to 'Create New Place', new_character_path, :class => "create_places_button" %>

  <%= gmaps4rails(@json) %>

  <% @characters.each do |character| %>

  <div class="places-preview-list-box">
        <div class="placelist" >
          <h3><%= character.name %></h3>
            <div class="places-edit-checkbox">
              <%= link_to '', edit_character_path(character), :class => "places-edit-sprite" %>
            </div><!--end  checkbox-->
        <div class="places-delete-checkbox">
            <%= link_to '', character, :class => "places-delete-sprite", method: :delete, data: { confirm: 'Are you sure you want to delete this place?' } %>
        </div><!--end edit checkbox-->
    </div> <!-- end placelist -->

 </div> <!-- end places previewlistbox -->

</div>

<% end %>

<%= render 'places-footer' %>

app/views/characters/mobile.html.erb
<ul>
	<li><a href="<%= character.address %>"><%= @character.name %></li>
	 </ul>

app/views/characters/new.html.erb
<%= render 'places-header' %>
<div class="white">
<%= render 'form' %>
</div>
<%= render 'places-footer' %>

app/views/characters/show.html.erb
<%= render 'places-header' %>

<h4 id="notice"><%= notice %></h4>

	<div class="white">
		<div class="container">

				<h2>
				 <%= @character.name %>
				</h2>
				 <h2>
				 <%= @character.address %>
				</h2>

			<%= link_to 'Edit this Place', edit_character_path(@character), :class => "places_button" %>
			<%= link_to 'Confirm Place', characters_path, :class => "places_button" %>
		
		</div><!-- END CONTAINER -->

	</DIV><!--  END WHITE -->


<%= render 'places-footer' %>

app/views/layouts/application.html.erb
  <!doctype html>
<html>
<head>
<meta charset="UTF-8">
<title>Virgil: A Simple Mobile UI</title>
<meta name="description" content="Virgil: A Simple Mobile UI. Virgil lets you simplify your smartphone to accessible core features.">
<meta name="keywords" content="Virgil, Mobile, User Interface, UI, simple phone layout, special needs technology">
<meta name="author" content="Dan Tashman">

 <link href='http://fonts.googleapis.com/css?family=Lato|Muli|Oxygen' rel='stylesheet' type='text/css'>


  <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
<script type="text/javascript" src="/assets/javascripts/bootstrap.min.js"></script>


  <%= stylesheet_link_tag    "application", :media => "all" %>
  	<%= stylesheet_link_tag 'style' %>
	<%= stylesheet_link_tag 'header-footer' %>
	<%= stylesheet_link_tag 'normalize' %>
	<%= stylesheet_link_tag 'gmaps4rails' %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %> 
    <%= yield :head %>
</head>

 <body>

    <%= yield %>
    <%= yield :scripts %>


</body>
</html>